// <auto-generated />
using Grapio.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grapio.Server.Migrations
{
    [DbContext(typeof(GrapioDbContext))]
    [Migration("20240329152305_Consumer")]
    partial class Consumer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Grapio.Server.FeatureFlag", b =>
                {
                    b.Property<string>("FlagKey")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Key");

                    b.Property<string>("Consumer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(150)")
                        .HasDefaultValue("*")
                        .HasColumnName("Consumer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Value");

                    b.HasKey("FlagKey", "Consumer");

                    b.ToTable("FeatureFlags");
                });
#pragma warning restore 612, 618
        }
    }
}
